import { format } from 'date-fns'
import { jsPDF } from 'jspdf'
import ExcelJS from 'exceljs'
import { HOTEL_NAME } from './reservation-terms'
import { getLogoDataUrl } from './reservation-document-html'
import { formatBdtForPdf } from './currency'
import { formatPaymentMethod } from './payment-method'

export type BeverageSaleExportRecord = {
  id: string
  saleNumber: string
  saleType: 'WALK_IN' | 'ROOM'
  subtotal: number
  totalAmount: number
  customerName: string | null
  customerPhone: string | null
  paymentMethod: string | null
  notes: string | null
  createdAt: string
  room?: { roomNumber: string } | null
  creator?: { name: string } | null
  items?: Array<{
    itemName: string
    quantity: number
    unitPrice: number
    lineTotal: number
  }>
}

export type BeverageSalesExportMeta = {
  filters?: {
    date: string
    type: string
    search: string
  }
  exportedAt?: Date
  generatedBy?: { name: string; email?: string; role?: string }
}

function formatGeneratedBy(user?: BeverageSalesExportMeta['generatedBy']): string {
  if (!user?.name) return '—'
  if (user.email) return `${user.name} (${user.email})`
  return user.name
}

function saleTypeLabel(saleType: string): string {
  return saleType === 'ROOM' ? 'Room charge' : 'Walk-in'
}

function guestOrRoomLabel(sale: BeverageSaleExportRecord): string {
  if (sale.saleType === 'ROOM') {
    return sale.room?.roomNumber ? `Room ${sale.room.roomNumber}` : '—'
  }
  return sale.customerName?.trim() || 'Walk-in'
}

function itemsSummary(sale: BeverageSaleExportRecord): string {
  if (!sale.items?.length) return '—'
  return sale.items.map((i) => `${i.quantity}× ${i.itemName}`).join(', ')
}

export function mapBeverageSaleToExportRow(
  sale: BeverageSaleExportRecord
): Record<string, string | number> {
  return {
    'Sale #': sale.saleNumber,
    Date: format(new Date(sale.createdAt), 'dd MMM yyyy'),
    Time: format(new Date(sale.createdAt), 'HH:mm'),
    Type: saleTypeLabel(sale.saleType),
    'Guest / Room': guestOrRoomLabel(sale),
    Phone: sale.customerPhone ?? '',
    Payment:
      sale.saleType === 'WALK_IN'
        ? formatPaymentMethod(sale.paymentMethod ?? 'CASH')
        : 'Room folio',
    Items: itemsSummary(sale),
    Subtotal: sale.subtotal,
    Total: sale.totalAmount,
    Staff: sale.creator?.name ?? '',
    Notes: sale.notes ?? '',
  }
}

export function beverageSalesExportFileName(ext: 'xlsx' | 'pdf'): string {
  return `hotel-beverage-sales-${format(new Date(), 'yyyy-MM-dd-HHmm')}.${ext}`
}

async function loadExportLogo(): Promise<{ dataUrl: string; base64: string } | null> {
  try {
    const dataUrl = await getLogoDataUrl()
    const base64 = dataUrl.includes(',') ? dataUrl.split(',')[1]! : dataUrl
    return { dataUrl, base64 }
  } catch {
    return null
  }
}

function triggerBrowserDownload(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  anchor.click()
  URL.revokeObjectURL(url)
}

function computeExportTotals(sales: BeverageSaleExportRecord[]) {
  return sales.reduce(
    (acc, sale) => ({
      subtotal: acc.subtotal + sale.subtotal,
      total: acc.total + sale.totalAmount,
    }),
    { subtotal: 0, total: 0 }
  )
}

export async function downloadBeverageSalesExcel(
  sales: BeverageSaleExportRecord[],
  meta: BeverageSalesExportMeta = {}
): Promise<void> {
  if (!sales.length) throw new Error('No beverage sales to export')

  const rows = sales.map(mapBeverageSaleToExportRow)
  const headers = Object.keys(rows[0])
  const exportedAt = meta.exportedAt ?? new Date()
  const filters = meta.filters ?? { date: 'All dates', type: 'All types', search: '—' }
  const totals = computeExportTotals(sales)

  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet('Beverage Sales')
  let row = 1

  sheet.mergeCells(row, 1, row, Math.max(headers.length, 4))
  sheet.getCell(row, 1).value = HOTEL_NAME
  sheet.getCell(row, 1).font = { bold: true, size: 16 }
  row += 1
  sheet.mergeCells(row, 1, row, Math.max(headers.length, 4))
  sheet.getCell(row, 1).value = 'Hotel Beverage Sales Report'
  sheet.getCell(row, 1).font = { bold: true, size: 12 }
  row += 2

  const info: [string, string | number][] = [
    ['Generated by', formatGeneratedBy(meta.generatedBy)],
    ['Exported', format(exportedAt, 'dd MMM yyyy, HH:mm')],
    ['Date', filters.date],
    ['Type', filters.type],
    ['Search', filters.search],
    ['Total records', sales.length],
    ['Grand total', totals.total],
  ]
  for (const [label, value] of info) {
    sheet.getCell(row, 1).value = label
    sheet.getCell(row, 1).font = { bold: true }
    sheet.getCell(row, 2).value = value
    row += 1
  }
  row += 1

  headers.forEach((header, index) => {
    const cell = sheet.getCell(row, index + 1)
    cell.value = header
    cell.font = { bold: true }
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE8F5E9' },
    }
  })
  row += 1

  for (const dataRow of rows) {
    headers.forEach((header, index) => {
      sheet.getCell(row, index + 1).value = dataRow[header]
    })
    row += 1
  }

  const totalRow = headers.map((header) => {
    if (header === 'Sale #') return 'Grand Total'
    if (header === 'Subtotal') return totals.subtotal
    if (header === 'Total') return totals.total
    return ''
  })
  totalRow.forEach((value, index) => {
    const cell = sheet.getCell(row, index + 1)
    cell.value = value
    cell.font = { bold: true }
  })

  headers.forEach((_, index) => {
    sheet.getColumn(index + 1).width = index === headers.indexOf('Items') ? 36 : 16
  })

  const buffer = await workbook.xlsx.writeBuffer()
  triggerBrowserDownload(
    new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    }),
    beverageSalesExportFileName('xlsx')
  )
}

export async function downloadBeverageSalesPdf(
  sales: BeverageSaleExportRecord[],
  meta: BeverageSalesExportMeta = {}
): Promise<void> {
  if (!sales.length) throw new Error('No beverage sales to export')

  const logo = await loadExportLogo()
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape', compress: true })
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 8
  const marginTop = 10
  const marginBottom = 10
  let y = marginTop

  const exportedAt = meta.exportedAt ?? new Date()
  const filters = meta.filters ?? { date: 'All dates', type: 'All types', search: '—' }
  const totals = computeExportTotals(sales)

  if (logo) {
    pdf.addImage(logo.dataUrl, 'PNG', marginX, y, 12, 12)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text(HOTEL_NAME, marginX + 14, y + 5)
    pdf.setFontSize(11)
    pdf.text('Hotel Beverage Sales Report', marginX + 14, y + 10)
  } else {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text(HOTEL_NAME, pageWidth / 2, y + 4, { align: 'center' })
    pdf.setFontSize(11)
    pdf.text('Hotel Beverage Sales Report', pageWidth / 2, y + 10, { align: 'center' })
  }

  y += 16
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  const metaLines = [
    `Exported: ${format(exportedAt, 'dd MMM yyyy, HH:mm')}`,
    `Generated by: ${formatGeneratedBy(meta.generatedBy)}`,
    `Date: ${filters.date} · Type: ${filters.type} · Search: ${filters.search}`,
    `Records: ${sales.length} · Grand total: ${formatBdtForPdf(totals.total)}`,
  ]
  for (const line of metaLines) {
    pdf.text(line, marginX, y)
    y += 4
  }
  y += 2

  const columns = [
    { header: 'Sale #', width: 28, value: (s: BeverageSaleExportRecord) => s.saleNumber },
    {
      header: 'Date/Time',
      width: 28,
      value: (s: BeverageSaleExportRecord) =>
        format(new Date(s.createdAt), 'dd MMM yyyy HH:mm'),
    },
    { header: 'Type', width: 18, value: (s: BeverageSaleExportRecord) => saleTypeLabel(s.saleType) },
    {
      header: 'Guest/Room',
      width: 28,
      value: (s: BeverageSaleExportRecord) => guestOrRoomLabel(s),
    },
    {
      header: 'Payment',
      width: 18,
      value: (s: BeverageSaleExportRecord) =>
        s.saleType === 'WALK_IN'
          ? formatPaymentMethod(s.paymentMethod ?? 'CASH')
          : 'Folio',
    },
    { header: 'Items', width: 52, value: (s: BeverageSaleExportRecord) => itemsSummary(s) },
    {
      header: 'Total',
      width: 20,
      value: (s: BeverageSaleExportRecord) => formatBdtForPdf(s.totalAmount),
    },
  ]

  const tableWidth = columns.reduce((sum, col) => sum + col.width, 0)
  const startX = marginX
  const rowHeight = 6

  const drawHeader = () => {
    pdf.setFillColor(232, 245, 233)
    pdf.rect(startX, y, tableWidth, rowHeight, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    let x = startX
    for (const col of columns) {
      pdf.text(col.header, x + 1, y + 4)
      x += col.width
    }
    y += rowHeight
  }

  drawHeader()
  pdf.setFont('helvetica', 'normal')

  for (const sale of sales) {
    if (y + rowHeight > pageHeight - marginBottom) {
      pdf.addPage()
      y = marginTop
      drawHeader()
      pdf.setFont('helvetica', 'normal')
    }
    let x = startX
    for (const col of columns) {
      const text = String(col.value(sale))
      const clipped = pdf.splitTextToSize(text, col.width - 2)[0] ?? ''
      pdf.text(clipped, x + 1, y + 4)
      x += col.width
    }
    y += rowHeight
  }

  pdf.save(beverageSalesExportFileName('pdf'))
}
