import { format } from 'date-fns'
import ExcelJS from 'exceljs'
import { jsPDF } from 'jspdf'
import { HOTEL_NAME } from './reservation-terms'
import { getLogoDataUrl } from './reservation-document-html'

export type TableExportMeta = {
  exportedAt?: Date
  generatedBy?: { name: string; email?: string; role?: string }
  infoRows?: [string, string | number][]
}

export type PdfColumnDef = {
  header: string
  width: number
  value: (row: Record<string, string | number>) => string
  align?: 'right'
}

const PDF_LINE_HEIGHT = 3.6
const PDF_CELL_PAD = 1.5

function formatGeneratedBy(user?: TableExportMeta['generatedBy']): string {
  if (!user?.name) return '—'
  if (user.email) return `${user.name} (${user.email})`
  return user.name
}

async function loadExportLogo(): Promise<{ dataUrl: string; base64: string } | null> {
  try {
    const dataUrl = await getLogoDataUrl()
    const base64 = dataUrl.includes(',') ? dataUrl.split(',')[1]! : dataUrl
    return { dataUrl, base64 }
  } catch {
    return null
  }
}

function triggerBrowserDownload(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  anchor.click()
  URL.revokeObjectURL(url)
}

export function tableExportFileName(prefix: string, ext: 'xlsx' | 'pdf'): string {
  return `${prefix}-${format(new Date(), 'yyyy-MM-dd-HHmm')}.${ext}`
}

export async function downloadTableExcel(options: {
  title: string
  sheetName?: string
  headers: string[]
  rows: Record<string, string | number>[]
  meta?: TableExportMeta
  fileName: string
  totalsRow?: (string | number)[]
}): Promise<void> {
  const { title, headers, rows, meta = {}, fileName, totalsRow } = options
  if (!rows.length) throw new Error('No records to export')

  const exportedAt = meta.exportedAt ?? new Date()
  const logo = await loadExportLogo()
  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet(options.sheetName ?? 'Report')
  let row = 1
  const colCount = headers.length

  if (logo) {
    const imageId = workbook.addImage({ base64: logo.base64, extension: 'png' })
    sheet.addImage(imageId, { tl: { col: 0.1, row: 0.1 }, ext: { width: 44, height: 44 } })
  }

  const textStartCol = logo ? 2 : 1
  sheet.mergeCells(row, textStartCol, row, Math.max(colCount, textStartCol + 2))
  sheet.getCell(row, textStartCol).value = HOTEL_NAME
  sheet.getCell(row, textStartCol).font = { bold: true, size: 16 }
  row += 1
  sheet.mergeCells(row, textStartCol, row, Math.max(colCount, textStartCol + 2))
  sheet.getCell(row, textStartCol).value = title
  sheet.getCell(row, textStartCol).font = { bold: true, size: 12 }
  row += 2

  const infoRows: [string, string | number][] = [
    ['Generated by', formatGeneratedBy(meta.generatedBy)],
    ['Exported', format(exportedAt, 'dd MMM yyyy, HH:mm')],
    ['Total records', rows.length],
    ...(meta.infoRows ?? []),
  ]

  for (const [label, value] of infoRows) {
    sheet.getCell(row, 1).value = label
    sheet.getCell(row, 1).font = { bold: true }
    sheet.getCell(row, 2).value = value
    row += 1
  }
  row += 1

  headers.forEach((header, index) => {
    const cell = sheet.getCell(row, index + 1)
    cell.value = header
    cell.font = { bold: true }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF5F5F5' } }
  })
  row += 1

  for (const dataRow of rows) {
    headers.forEach((header, index) => {
      sheet.getCell(row, index + 1).value = dataRow[header] ?? ''
    })
    row += 1
  }

  if (totalsRow?.length) {
    totalsRow.forEach((value, index) => {
      const cell = sheet.getCell(row, index + 1)
      cell.value = value
      cell.font = { bold: true }
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFBEB' } }
    })
  }

  headers.forEach((header, index) => {
    const col = sheet.getColumn(index + 1)
    col.width = Math.min(
      48,
      Math.max(header.length + 2, ...rows.map((r) => String(r[header] ?? '').length + 2))
    )
  })

  const buffer = await workbook.xlsx.writeBuffer()
  triggerBrowserDownload(
    new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    }),
    fileName
  )
}

export async function downloadTablePdf(options: {
  title: string
  columns: PdfColumnDef[]
  rows: Record<string, string | number>[]
  meta?: TableExportMeta
  fileName: string
  summaryLine?: string
  totalsRow?: Record<string, string | number>
}): Promise<void> {
  const { title, columns, rows, meta = {}, fileName, summaryLine, totalsRow } = options
  if (!rows.length) throw new Error('No records to export')

  const logo = await loadExportLogo()
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape', compress: true })
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 10
  const marginBottom = 10
  let y = 10
  const exportedAt = meta.exportedAt ?? new Date()

  if (logo) {
    pdf.addImage(logo.dataUrl, 'PNG', marginX, y, 12, 12)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text(HOTEL_NAME, marginX + 16, y + 5)
    pdf.setFontSize(11)
    pdf.text(title, marginX + 16, y + 10)
    y += 16
  } else {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text(HOTEL_NAME, marginX, y + 4)
    pdf.setFontSize(11)
    pdf.text(title, marginX, y + 10)
    y += 14
  }

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.text(`Exported: ${format(exportedAt, 'dd MMM yyyy, HH:mm')}`, marginX, y)
  y += 3.8
  pdf.text(`Generated by: ${formatGeneratedBy(meta.generatedBy)}`, marginX, y)
  y += 3.8
  if (summaryLine) {
    pdf.text(summaryLine, marginX, y)
    y += 3.8
  }
  pdf.text(`Total records: ${rows.length}`, marginX, y)
  y += 6

  const tableWidth = columns.reduce((sum, col) => sum + col.width, 0)
  let colX = marginX

  const columnLeftX = (index: number) => {
    let x = marginX
    for (let i = 0; i < index; i++) x += columns[i].width
    return x
  }

  const columnRightX = (index: number) => columnLeftX(index) + columns[index].width - PDF_CELL_PAD

  const drawRightAligned = (text: string, colIndex: number, baselineY: number) => {
    pdf.text(text, columnRightX(colIndex) - pdf.getTextWidth(text), baselineY)
  }

  const drawHeader = () => {
    pdf.setFillColor(245, 245, 245)
    pdf.rect(marginX, y - 4, tableWidth, 6, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    colX = marginX + PDF_CELL_PAD
    for (let i = 0; i < columns.length; i++) {
      const col = columns[i]
      if (col.align === 'right') {
        drawRightAligned(col.header, i, y)
      } else {
        pdf.text(col.header, colX, y)
      }
      colX += col.width
    }
    y += 6
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(6.5)
  }

  drawHeader()

  for (const row of rows) {
    const lines = columns.map((col, index) => {
      const value = col.value(row)
      if (col.align === 'right') return [value]
      return pdf.splitTextToSize(value, Math.max(columns[index].width - PDF_CELL_PAD * 2, 8))
    })
    const maxLines = Math.max(...lines.map((l) => l.length), 1)
    const rowHeight = maxLines * PDF_LINE_HEIGHT + 1.2

    if (y + rowHeight > pageHeight - marginBottom - (totalsRow ? 10 : 0)) {
      pdf.addPage()
      y = 10
      drawHeader()
    }

    for (let i = 0; i < columns.length; i++) {
      const col = columns[i]
      if (col.align === 'right') {
        drawRightAligned(lines[i][0] ?? '', i, y)
      } else {
        pdf.text(lines[i], columnLeftX(i) + PDF_CELL_PAD, y)
      }
    }
    y += rowHeight
  }

  if (totalsRow) {
    y += 1.5
    pdf.setFillColor(255, 251, 235)
    pdf.rect(marginX, y - 3.5, tableWidth, PDF_LINE_HEIGHT + 3, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(6.5)
    for (let i = 0; i < columns.length; i++) {
      const col = columns[i]
      const value = col.value(totalsRow)
      if (col.align === 'right') {
        drawRightAligned(value, i, y)
      } else if (i === 0) {
        pdf.text(value, columnLeftX(i) + PDF_CELL_PAD, y)
      }
    }
  }

  pdf.save(fileName)
}
